### PR TITLE
sp imroves

### PR DESCRIPTION
**Pull request by byronbest**

### CODE REVIEW

**Comment by rafaqz** [comment]
Thanks so much for fixing all these things!!! It does all really need a proof-read.

**Comment by byronbest** [comment]
My pleasure! I enjoyed reading your Julia. I instantly see any typos with
no effort at all.

Thanks for your work!
Byron

**Comment by rafaqz** [comment]
Wish I had that skill! I instantly make those typos with no effort at all...

What kind of things are you looking at doing with DynamicGrids? (If you don't mind me asking)

**Comment by byronbest** [comment]
I found you via SciML and JuliaCon 2020
Thought you'd rather not have trivial typos.
Wondering about offset arrays vs views, and loading the arrays into CUDA to use GPU
Maybe check out the MIT 18.S191 including convolutions, neighborhoods and all that.
Seems similar, with some really cool indexing
I realize your special sauce is chaining rules more than indexing arrays!

**Comment by rafaqz** [comment]
Yeah CUDA was always a goal. It actually ran on GPUarrays a year ago! but I dropped it.

The main reason not to use GPUs is the kinds of problems that limit our simulation performance at cesar are nearly always in a `ManualRule` - like population/gdp driven human dispersal rules, or simulations of random wind/storm dispersal. If you do this on GPU you have to deal with race conditions - because any cell can write to any other cell at any time. There is `atomic_add` in CUDA.jl but GPU locks are expensive, and it would still require users using that in their code instead of `+`. When Cassete/IRTools, KernelAbstractions.jl are all mature I will have another go. 

On top of that, the worst performance bottlenecks are usually for when you need replicates of stochastic simulations - and you can just use all your CPUs for that.

The other option is maintaining GPU and CPU arrays in `SimData` and copying data back and for between `Rule/ManualRule` in `sequencerules.jl`, and letting all sims without `ManualRule` just run entirely on GPU.

We could totally drop OffsetArrays.jl and use a view instead, that's a good point! It's a fairly arbitrary decision I made after a year using julia. But notice that none of the internal code uses the offset array anyway - its just for user rules. It's quicker to index into the parent and just do the radius shift manually in `maprule`. The same would probably be true for `SubArray`. So it's not a high priority to change.

As for convolutions, I did some of that course the other day! and put this in: https://github.com/cesaraustralia/DynamicGrids.jl/issues/58

Definitely there is room for optimizations on more formal analytic functions. A lot of my focus has been on getting performance on heterogeneous, non-analytic rules as a baseline, as it can be stifling for ecologists to be stuck with analytic models. But we should be able to e.g. do a single pass using a Fourier transform of the whole grid instead of running Gaussian dispersal kernels. That would happen in `sequencerules.jl` for any `AnalyticRule` - they would get diverted to whole-grid analytic methods.

**Comment by rafaqz** [comment]
BTW the way we load neighborhoods on CPU here would be an order of magnitude faster than the methods they use in the course - I'm already reducing reads from the main array down to 2x the minimum possible by caching reads in local buffers.

**Comment by byronbest** [comment]
Static arrays, each step reads from source and writes to sink, then next
step swap source and sink. Each timestep uses valid data, no race
conditions. Since the neighborhood is local, we should be able to
distribute the work for large arrays by tiling, with a little overlap.
I was hoping that Julia could do the optimization better than I could!

**Comment by rafaqz** [comment]
Sure there are no race conditions with neighborhood rules. But we use a lot of models that do have race conditions:
https://github.com/cesaraustralia/Dispersal.jl/blob/master/src/rules/human.jl#L244-L258

So I'm not really motivated to do parallel neighborhoods either - we just do parallel at the level of whole simulations.

**Comment by byronbest** [comment]
As I've always suspected, you know what you're doing, and I better shut up
before I reveal my ignorance lol

**Comment by rafaqz** [comment]
No these are all good questions lol, tiling would be great. Parallel or GPU seems obvious and are useful in a lot of cases, they're just not actually useful to me in practice so they aren't implemented. I should make these things a lot clearer in the docs.

**Comment by byronbest** [comment]
From the point of view of every cell, the rules "see" a View of local and
related data, that was where I questioned OffsetArray and went off about it.
I'm still seeing amazing things in Julia. Thought of you when I saw a
convolution done by sending the neighborhood as a "filter" in terms of
local offsets, the point being Julia was doing the hard stuff, all they had
to do was use the 'cu()' function to put the array in GPU memory, to get
100x speedup!

**Comment by rafaqz** [comment]
Yeah it's amazing how automated that stuff can get. At some stage I'm going to  facilitate using those tools in `AnalyticRule`, which should be able to run arbitrary kernels from DSP.jl or ImageFiltering.jl as if they are just another rule in the sequence.

With `OffsetArray` will notice that ImageFiltering.jl also uses OffsetArrays and their own hacked offset array called `BoundsArray` or something, instead of views. I think for the same reason.

**Pull request merged**
