### PR TITLE
start generalising dimensions

### PR DESCRIPTION
**Pull request by rafaqz**
@MartinuzziFrancesco this is a start on generalising the neighborhoods, rule mapping code and rendering to be N-dimensional.

I could possible swap a bunch of the internals to just use KernelAbstractions.jl and take the small performance hit, then everything will work in arbitrary dimensions. It should already be pretty close to being generic on GPU.

### CODE REVIEW

**Comment by MartinuzziFrancesco** [comment]
This is wonderful, I will keep an eye on this and try to modify CellularAutomata.jl to work in this setting. Thanks for starting this work!

**Comment by rafaqz** [comment]
Working! On this branch:

```julia
using DynamicGrids, Crayons
init = zeros(100)
init[40] = true
init[71] = true
# Or define it from scratch (yes this is actually the whole implementation!)
rule110 = Neighbors(Moore(1; ndims=1)) do data, hood, C, I
    L, R = neighbors(hood)
    (C + R + C * R + L * C * R) % 2
end
output = REPLOutput(init; tspan=1:200, store=true, fps=10, color=Crayon(foreground=:red, background=:black, bold=true))
sim!(output, rule110)
```


```
               █       █       █       █      █       █       █       █
             █ █     █ █     █ █     █ █    █ █     █ █     █ █     █ █
           █   █   █   █   █   █   █   █  █   █   █   █   █   █   █   █
         █ █ █ █ █ █ █ █ █ █ █ █ █ █ █ ██ █ █ █ █ █ █ █ █ █ █ █ █ █ █ █
       █                              ██                              █
     █ █                            ████                            █ █
   █   █                          ██  ██                          █   █
 █ █ █ █                        ████████                        █ █ █ █
       █                      ██      ██                      █       █
     █ █                    ████    ████                    █ █     █ █
   █   █                  ██  ██  ██  ██                  █   █   █   █
 █ █ █ █                ████████████████                █ █ █ █ █ █ █ █
```

**Comment by rafaqz** [comment]
@MartinuzziFrancesco if you want to build on this, these are some examples of building rules and packages on top op DynamicGrids.jl:

https://github.com/cesaraustralia/DynamicGrids.jl/blob/master/src/life.jl
https://github.com/EcoJulia/MetacommunityDynamics.jl
https://github.com/cesaraustralia/Dispersal.jl

**Comment by MartinuzziFrancesco** [comment]
this looks neat, I'll start digging in the examples as soon as I can

**Comment by rafaqz** [comment]
Now the `GifOutput` and e.g. DynamicGridsGtk/DynamicGridsInteract.jl should work:

```julia
init = zeros(Int, 200)
init[150] = true
filename = "test_1d_gifoutput.gif"
output = GifOutput(init; filename=filename, text=nothing, tspan=1:50)
sim!(output, rule110)
````
test_1d_gifoutput

**Pull request merged**
